"""support for admin in users model

Revision ID: d3c8e160f118
Revises: bdd676352cd4
Create Date: 2024-06-22 14:22:57.760291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c8e160f118'
down_revision = 'bdd676352cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the 'admin' column with a server default value of False
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    
    # Remove the server default after the column is populated
    op.alter_column('user', 'admin', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
